### ISSUE TITLE
Needs a dds library that doesn't exist

### ISSUE THREAD

**Issue by samth** [ponycloud/twilight#3]
You removed the dependency on `"dds"` but it's required in `component/addr.rkt` here: https://github.com/ponycloud/twilight/blob/master/twilight/component/addr.rkt#L12

**Comment by mordae** [comment]
I know. As soon as all the functionality from `twilight/component/*.rkt` gets merged to the new infrastructure, I will delete those files and get rid of the warning. But thanks for keeping your eye on things! :-)
